name = "automake"
version = "1.16.4"
desc = "A GNU tool for automatically creating Makefiles"
archs = 1
platforms = 1
source = "https://ftp.gnu.org/gnu/automake/automake-1.16.4.tar.gz"
licenses = [ "GPLv2" ]
requires = []
requires_build = []
target_dir = "automake-1.16.4"
vars = []
script = "echo Nothing todo"