name = "make-bin"
version = "0.4.3-3"
desc = "GNU make utility to maintain groups of programs"
archs = 1
platforms = 1
source = "https://ftp5.gwdg.de/pub/linux/archlinux/core/os/x86_64/make-4.3-3-x86_64.pkg.tar.zst"
licenses = [ "GPLv3" ]
requires = []
requires_build = []
target_dir = "usr"
vars = []
script = "echo Binary Package -> Nothing todo"